buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
}

apply plugin: 'org.spongepowered.mixin'

base {
    archivesName = "c2meF-opts-dfc-mc${minecraft_version}-${mod_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation 'org.jspecify:jspecify:1.0.0'
    implementation fileTree(dir: '../libs', include: '*.jar')
}

mixin {
    add sourceSets.main, "c2me_opts_dfc.refmap.json"
    config "c2me_opts_dfc.mixins.json"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    filesMatching(['META-INF/mods.toml']) {
        expand project.properties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    finalizedBy 'reobfJar'
}
